;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2022/1/9 14:24:47

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1005	1005	; 二分查找 C-API\查找\二分查找.html
#define IDH_1001	1001	; 快速排序 C-API\排序\快速排序.html
#define IDH_1000	1000	; 冒泡排序 C-API\排序\冒泡排序.html
#define IDH_1004	1004	; 进制运算 C-API\数据处理\进制运算.html
#define IDH_1003	1003	; 数组翻转 C-API\数据处理\数组翻转.html
#define IDH_1002	1002	; 字符数组 C-API\数据处理\字符数组.html
