;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2022/1/9 14:24:47

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1005=C-API\查找\二分查找.html	; 二分查找
IDH_1001=C-API\排序\快速排序.html	; 快速排序
IDH_1000=C-API\排序\冒泡排序.html	; 冒泡排序
IDH_1004=C-API\数据处理\进制运算.html	; 进制运算
IDH_1003=C-API\数据处理\数组翻转.html	; 数组翻转
IDH_1002=C-API\数据处理\字符数组.html	; 字符数组
