;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2022/1/10 13:03:48

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1020	1020	; 二分查找 C-API\查找\二分查找.html
#define IDH_1003	1003	; 快速排序 C-API\排序\快速排序.html
#define IDH_1002	1002	; 冒泡排序 C-API\排序\冒泡排序.html
#define IDH_1017	1017	; 二进制求和 C-API\数据处理\进制运算\二进制求和.html
#define IDH_1018	1018	; 十进制转N进制 C-API\数据处理\进制运算\十转N.html
#define IDH_1019	1019	; 十进制转二进制 C-API\数据处理\进制运算\十转二.html
#define IDH_1010	1010	; 取子数组元素 C-API\数据处理\整型数组\取子数组元素.html
#define IDH_1011	1011	; 数据重置 C-API\数据处理\整型数组\数据重置.html
#define IDH_1013	1013	; 数组最小值 C-API\数据处理\整型数组\数组最小值.html
#define IDH_1016	1016	; 整型数字拆分 C-API\数据处理\整型数组\整型数字拆分.html
#define IDH_1015	1015	; 整型数字合并 C-API\数据处理\整型数组\整型数字合并.html
#define IDH_1014	1014	; 整型数组翻转 C-API\数据处理\整型数组\数组翻转.html
#define IDH_1012	1012	; 整形数组最大值 C-API\数据处理\整型数组\数组最大值.html
#define IDH_1004	1004	; 二维转一维 C-API\数据处理\字符数组\二维转一维.html
#define IDH_1009	1009	; 翻转 C-API\数据处理\字符数组\翻转.html
#define IDH_1007	1007	; 数据重置 C-API\数据处理\字符数组\数据重置.html
#define IDH_1008	1008	; 数组转整型 C-API\数据处理\字符数组\数组转整型.html
#define IDH_1005	1005	; 字符串分割 C-API\数据处理\字符数组\字符串分割.html
#define IDH_1006	1006	; 字符串拷贝 C-API\数据处理\字符数组\字符串拷贝.html
#define IDH_1000	1000	; 交换 C-API\原子操作\整型\交换.html
#define IDH_1001	1001	; CHAR 与 INT 的相互转换 C-API\原子操作\转换\字符型与整型互转.html
