;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2022/1/10 13:03:48

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1020=C-API\查找\二分查找.html	; 二分查找
IDH_1003=C-API\排序\快速排序.html	; 快速排序
IDH_1002=C-API\排序\冒泡排序.html	; 冒泡排序
IDH_1017=C-API\数据处理\进制运算\二进制求和.html	; 二进制求和
IDH_1018=C-API\数据处理\进制运算\十转N.html	; 十进制转N进制
IDH_1019=C-API\数据处理\进制运算\十转二.html	; 十进制转二进制
IDH_1010=C-API\数据处理\整型数组\取子数组元素.html	; 取子数组元素
IDH_1011=C-API\数据处理\整型数组\数据重置.html	; 数据重置
IDH_1013=C-API\数据处理\整型数组\数组最小值.html	; 数组最小值
IDH_1016=C-API\数据处理\整型数组\整型数字拆分.html	; 整型数字拆分
IDH_1015=C-API\数据处理\整型数组\整型数字合并.html	; 整型数字合并
IDH_1014=C-API\数据处理\整型数组\数组翻转.html	; 整型数组翻转
IDH_1012=C-API\数据处理\整型数组\数组最大值.html	; 整形数组最大值
IDH_1004=C-API\数据处理\字符数组\二维转一维.html	; 二维转一维
IDH_1009=C-API\数据处理\字符数组\翻转.html	; 翻转
IDH_1007=C-API\数据处理\字符数组\数据重置.html	; 数据重置
IDH_1008=C-API\数据处理\字符数组\数组转整型.html	; 数组转整型
IDH_1005=C-API\数据处理\字符数组\字符串分割.html	; 字符串分割
IDH_1006=C-API\数据处理\字符数组\字符串拷贝.html	; 字符串拷贝
IDH_1000=C-API\原子操作\整型\交换.html	; 交换
IDH_1001=C-API\原子操作\转换\字符型与整型互转.html	; CHAR 与 INT 的相互转换
